Document/ivyportal 16025 case widget complex filters g UI tests screenshots documentation
axonivy-market/portal pull request #529
Opened 2024-03-05 02:32 UTC by ntloc-axonivy

![case-task-widget-filter-combine](https://github.com/axonivy-market/portal/assets/121596218/6e084a55-1de9-40ca-a11d-25c7cd50597e)

Document for complex filter

2024-03-05 08:51 UTC, nhthinh-axonivy requested changes

2024-03-05 08:51 UTC, nhthinh-axonivy commented on Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-case-widget.rst
> +There are additional fields dependent on the operator and many of specific filters for each field type. Below is the list of filterable columns and their corresponding filter
Remove "of" -> There are additional fields dependent on the operator and many specific filters for each field type. Below is the list of filterable columns and their corresponding filter

2024-03-05 08:51 UTC, nhthinh-axonivy commented on Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-case-widget.rst
> +Please refer to :ref:`Complex Filter <complex-filter>` for more details.
Remove "," -> string and some only accept a string in a special format such as date-time.

2024-03-05 08:51 UTC, nhthinh-axonivy commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +     | Specifically, it will be from the first day of the current year/month/week to end the last day of current year/month/week.
Specifically, it will be from the first day of the current year/month/week to the end of the last day of the current year/month/week

2024-03-05 14:08 UTC, phochstr reviewed
Sorry, lots of little things to correct.
After correction, merge.

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-case-widget.rst
> +   - ``startTimestamp`` and ``endTimestamp``: Case's created date and finished date
Case's created date and finished date -->

created date and finished date of the Case

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +    This configuration implies finding all cases where the state is OPEN, the name contains 'Mike', and they were created today.
This filter configuration finds all cases in state OPEN, with their name containing 'Mike', created today.

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +- Click on ``Save filter`` button, then input filter set name and click ``Save``.
input filter set name --> enter the filter set name

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +- Select a filter set name to apply it, and deselect it to remove the filter set.
filter set name --> filter set

Yes, you click on the name, but you actually select the whole thing.

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +Filter Set Management
I'd say that creating, i.e., saving, a filter set is also part of the filter set management - we have CRUD as management operations.

But leave as is.

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +     | Results include only records where the data in the column created by current user.
Results include only records where the data in the column created by current user.
-->
Results include only records where the data in the column has been created by current user.

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +     | Results include only records where the data in the column does not ends with the value in the filter.
ends --> end

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +     | Results include only records where the data in the column ends with the value in the filter.
ends --> end

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +     | Results include only records where the data in the column does not starts with the value in the filter.
starts --> start

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +     | *Example*: Find all cases with Invoice Due Date within the next 2 years
here, you talk about 2 years.Below, the difference is 3 weeks ... pls. adjust.

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +     | Results include only records where the date in the column falls within the selected range specified in the filter.
falls within the selected range specified in the filter.
-->
falls within the range specified in the filter.

The filter provides the selection range - as a range.

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +     | Results include only records where the date in the column falls within the selected range specified in the filter.
falls within the selected range specified in the filter.
-->
falls within the range specified in the filter.

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +     | within the period from ``2/1/2022 00:00:00`` to ``2/29/2024 23:59:59``.
Copy & paste error - Current Month <> Last 2 years.
Adjust to selection above.

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +     | Results include only records where the date in the column falls within the selected range specified in the filter.
falls within the selected range specified in the filter.
-->
falls within the range specified in the filter.

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +     | Results include only records where presence of data in the column.
Results include only records where presence of data in the column.
-->
 Results include only records that contain data in the column.

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +     | Results include only records where absence of data in the column.
Results include only records where presence of data in the column.
-->
 Results include only records that contain no data in the column.

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +     | Results include only records where the data in the column is greater than or the same as the value in the filter.
Results include only records where the data in the column is greater than or the same as the value in the filter.
-->
Results include only records where the data in the column is greater than or equal to the value in the filter.

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +     | Results include only records where the data in the column is less than or the same as the value in the filter.
the same as --> equal to

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +     | Results include only records where the data in the column does not matches the value in the filter.
matches --> match

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +     | Results include only records where the data in the column matches the value in the filter.
matches --> match

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +     | Results include only records where the data in the column not contains the value in the filter.
Results include only records where the data in the column not contains the value in the filter.
-->
 Results include only records where the data in the column **does not contain** the value in the filter.

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +     | Results include only records where the data in the column does not matches the value in the filter.
matches --> match

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +- To search for a filter set, type the search value into the input field at the top of every columns.
columns --> column

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
> +     | Results include only records where the data in the column not matches the value in the filter.
not matches
-->
does not match

2024-03-05 14:08 UTC, phochstr commented on Documentation/portal-guide/source/portal-user-guide/new-dashboard/index.rst
> +By clicking on the ``Filter`` button, you can define configuration for your widget, and get a preview of it by clicking on the
define configuration --> define the configuration

If I click on the apply button, do I only get a preview, or do I save the configuration?

2024-03-06 07:10 UTC, ntloc-axonivy commented on Documentation/portal-guide/source/portal-user-guide/new-dashboard/index.rst
> +By clicking on the ``Filter`` button, you can define configuration for your widget, and get a preview of it by clicking on the
No, just to get a preview. Previously, it was named the "Preview" button. After the new design, it has been changed to "Apply"

2024-03-06 08:53 UTC, merged